config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#show', defaults: {page: 'home'}, as: :home

  get :':page', to: 'pages#show', as: :page, constraints: {
    page: Regexp.new((PagesController::PAGES - ['home']).join('|'))
  }

  get :about, to: 'pages#about'
  get :faq, to: 'pages#faq'
  get :terms, to: 'pages#terms'
  get :privacy, to: 'pages#privacy'

  resources :currencies, only: [:index, :show]
  resources :indexes, only: [:index, :show]

  post :signup, to: 'users#create'
  patch :signup, to: 'users#update'

  get :unsubscribe, to: 'users#unsubscribe', as: :unsubscribe_user

  scope module: :user do
    get :'email/confirm', to: 'email#confirm', as: :confirm_email

    get :'phone/confirmation/resend', to: 'phone#resend_confirmation_code',
                                      as: :resend_phone_confirmation_code

    get :login, to: 'sessions#new'
    post :login, to: 'sessions#create'
    get :logout, to: 'sessions#destroy'

    resource :account, controller: :account, only: :new
    get :account, to: redirect('/account/dashboard')
    namespace :account do
      resource :dashboard, controller: :dashboard, only: :show
    end

    get :portfolio, to: redirect('/portfolio/currencies')
    namespace :portfolio do
      resources :currencies, controller: :currency_holdings, only: :index
      resources :indexes, controller: :tracked_indexes, only: :index
    end

    get :transactions, to: redirect('/transactions/overview')
    namespace :transactions do
      resources :deposits, only: :index
      resources :rebalancings, only: :index
      resources :withdrawals, only: :index
      get :report, to: 'reports#download'
    end
    get :'/transactions/withdrawals/:id/confirm', # FIXME: Can't expose ID!
      to: 'transactions/withdrawals#confirm_by_email',
      as: :confirm_withdrawal_by_email

    get :settings, to: redirect('/settings/account')
    scope :settings do
      resource :account, controller: :account, only: :show
      resource :email, controller: :email, only: :show
      resource :phone, controller: :phone, only: :show
      resource :security, controller: :security, only: :show
    end
  end

  get :admin, to: redirect('/admin/users')
  namespace :admin do
    resources :users, only: :index
    resources :currencies, only: :index
    resources :valuations, only: :index

    mount Sidekiq::Web, at: :jobs
  end

  if Rails.env.development?
    namespace :security do
      resources :violations, only: :create
    end

    mount LetterOpenerWeb::Engine, at: :emails

    get :'sms/:text', to: proc { |request|
      [200, {}, [CGI.unescape(request['PATH_INFO'][5..-1])]]
    }, as: :sms_opener_web
  end
end

app/views/modules/footer/_index.html.erb
<footer class="footer">
  <div class="container">
    <div class="columns">
      <div class="column" style="display: flex; justify-content: center;">
        <div style="text-align: center">
          <%= image_tag asset_pack_path('images/logos/crypto_index.svg'), class: 'logo', style: 'margin: 1em auto', size: '28x28' %>
          <small>CryptoIndex</small>
        </div>
      </div>

      <div class="column is-hidden-mobile">
        <nav class="menu">
          <p class="menu-label">
            Currencies
          </p>

          <ul class="menu-list">
            <li><%= link_to 'View All', '/currencies' %></li>
            <%
              Index.market10.currencies.sort_by(&:market_cap_usd).
                reverse.first(6).sort_by(&:title).map do |currency|
            %>
              <li>
                <%= link_to currency.title, "/currencies/#{currency.name}" %>
              </li>
            <% end %>
          </ul>
        </nav>
      </div>

      <div class="column is-hidden-mobile">
        <nav class="menu">
          <p class="menu-label">
            CryptoIndex
          </p>

          <ul class="menu-list">
            <li><%= link_to 'FAQ', '/faq' %></li>
            <li><%= link_to 'About Us', '/about' %></li>
            <li><%= link_to 'Log In', '/login' %></li>
          </ul>
        </nav>
      </div>

      <div class="column is-hidden-mobile">
        <nav class="menu">
          <p class="menu-label">
            Legal
          </p>

          <ul class="menu-list">
            <li><%= link_to 'Terms & Conditions', '/terms' %></li>
            <li><%= link_to 'Privacy Policy', '/privacy' %></li>
          </ul>
        </nav>
      </div>
    </div>

    <div class="columns" style="margin-top: 1em">
      <div class="column">
        <div class="content is-gray is-size-7 has-text-centered">
          <p>
            CryptoIndex offers a software service that automatically manages customers' portfolios, executes trades on their behalf, and holds digital assets in individual sub-accounts. It does not provide index or mutual funds, nor is it regulated as such a provider.
            Nothing on this website is intended to constitute investment advice. Customers are advised to seek the counsel of a qualified, independent financial adviser before forming a decision as to the appropriateness of investing through CryptoIndex.
            Past performance is not indicative of future performance. Cryptocurrencies are a highly volatile asset class, and customers should have no expectation of attaining similar results to those possible through historical investment with CryptoIndex Furthermore, customers must accept the possibility of total loss.
            Customer portfolios may diverge from the indexes they track, both in terms of asset allocation and of performance. As such, there is no guarantee that your portfolio's asset allocation will match those of the indexes being tracked, nor is there any guarantee that your performance returns will be as high.
            Before deciding whether to avail of the services of CryptoIndex customers are required to read, comprehend, and agree to its <%= link_to 'terms and conditions', terms_path, style: 'color: gray; text-decoration: underline;' %>.
          </p>
        </div>
      </div>
    </div>
  </div>
</footer>